name: crud_riverpod
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  intl: ^0.17.0
  auto_route: ^5.0.4
  flutter_riverpod: ^2.2.0
  flutter_slidable: ^2.0.0
  shared_preferences: ^2.0.17
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.16
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4
  pull_to_refresh: ^2.0.0
  get_it: ^7.6.0
  connectivity_plus: ^4.0.1
  flutter_remix: ^0.0.3





dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/image/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
